
spring:
  thymeleaf:
    cache: false
    mode: HTML

  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/ms?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    #spring的druid配置
    initialSize: 1
    minIdle: 1
    maxActive: 2
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true


    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500


  redis:
    host: 182.92.169.128
    port: 6379
    password: 123456
  resources:
    add-mappings: true
    chain:
      cache: true
      enabled: true
      html-application-cache: true
    static-locations: classpath:/static/


  rabbitmq:
    host: 182.92.169.128
    port: 5672
    username: hwm
    password: 123456
    virtual-host: /
    listener:
      simple:
        concurrency: 10 #消费者数量
        max-concurrency: 10
        prefetch: 1    #每次从队列取1个
        auto-startup: true
        default-requeue-rejected: true  #消费者消费失败后从新加入到队列中
    template:
      retry:
        enabled: true



mybatis:
  type-aliases-package: com.hwm.domain
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000

  mapper-locations: classpath:dao/*.xml

logging:
  level:
    com.hwm.dao: debug
